---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: EMISHAW/taskmanager:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: taskmanager
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: taskmanager
